kind: Deployment
apiVersion: apps/v1
metadata:
  name: mft-destagent
  namespace: mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mft-destagent
  template:
    metadata:
      labels:
        app: mft-destagent
        deploymentconfig: mft-destagent
    spec:
      volumes:
        - name: mqmft-agent-config-map
          configMap:
            name: mft-agent-conf
            defaultMode: 420
        - name: mqmft-nfs
          persistentVolumeClaim:
            claimName: pvc-destagent
      containers:
        - resources: {}
          readinessProbe:
            exec:
              command:
                - agentready
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /mnt/termination-log
          name: mft-destagent
          livenessProbe:
            exec:
              command:
                - agentalive
            initialDelaySeconds: 90
            timeoutSeconds: 5
            periodSeconds: 90
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: MFT_AGENT_NAME
              value: DESTAGENT
            - name: LICENSE
              value: accept
            - name: MFT_AGENT_CONFIG_FILE
              value: /mqmftcfg/agentconfig/mqmftcfg.json
            - name: MFT_MOUNT_PATH
              value: /mountpath
            - name: MFT_LOG_LEVEL
              value: "info"
          imagePullPolicy: Always
          volumeMounts:
            - name: mqmft-agent-config-map
              mountPath: /mqmftcfg/agentconfig
            - name: mqmft-nfs
              mountPath: /mountpath
          terminationMessagePolicy: File
          image: >-
             docker.io/ibmcom/mqmft:latest
      restartPolicy: Always
