apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-destagent
  namespace: mq
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi